### ISSUE TITLE
Remove DarkSky dependency in Weather Plugin

### ISSUE THREAD

**Issue by eSoares** [llimllib/limbo#181]
In recent news Dark Sky was acquired by Apple and they will stop accepting new signups to use the API. 
Current API users will work until end 2021. (Source of information: https://blog.darksky.net/dark-sky-has-a-new-home/)

Currently the [weather plugin](https://github.com/llimllib/limbo/blob/master/limbo/plugins/weather.py) uses Dark Sky API. I suggest to move away form it, since new users would be impossible to use the register, get an API key and use the plugin.

**Comment by llimllib** [comment]
Weather APIs are a pain in the butt! I tried a bunch out when I was implementing weather, but most have terrible search functions, super restricted data, or both.

I'd much prefer to use one without an API key, but would prefer a decent search + api key to no key and a poor search function. Particularly I'd like the search function to return good results for US zip codes, which was a problem last time I checked.

Open to suggestions!

**Comment by eSoares** [comment]
I have used in the past [OpenWeather](https://openweathermap.org/api) API, from their [pricing](https://openweathermap.org/price) page the limits look acceptable for the plugin.

An alternative without any API key needed is [wttr.in](http://wttr.in).
More info: https://github.com/chubin/wttr.in

**Comment by llimllib** [comment]
OpenWeather was what I used initially. I switched to yahoo 3 years ago because the search function was a lot better: https://github.com/llimllib/limbo/commit/0a27f0ffe439f3c8891eceed34893d1158e53229#diff-f291ee819880fbed672999e9412f3c28

Then when yahoo discontinued, I switched to mapbox & dark sky: https://github.com/llimllib/limbo/commit/f0980f20f733b670debcae454b167da32c57a044#diff-f291ee819880fbed672999e9412f3c28

I _think_ I switched away from openweather both because they required an API key while yahoo didn't at the time, and because its search function was not very good. It may have gotten better, I don't know

**Comment by llimllib** [comment]
all this nonsense kind of makes me want to return to just scraping a web page
