### ISSUE TITLE
msg.get("text", "")

### ISSUE THREAD

**Issue by TetraEtc** [llimllib/limbo#61]
Why do the standard plugins use msg.get("text", "") instead of just referencing msg["text"]. They're DICT type objects after all and indexing in that manner would be more Pythonic as far as I can tell.

**Comment by llimllib** [comment]
Because a plugin can't guarantee that the `msg` dictionary passed to it contains a text element; the msg  comes from outside of limbo. This way, instead of throwing a `KeyError`, the plugin will process successfully.

Limbo will handle a plugin throwing a KeyError properly, so it's OK if a plugin *does* choose to check that way, but it will lead to unnecessary noise in the log.

I don't think either is any more "pythonic" than the other.

Is that a satisfactory answer?

(Going to get to your plugin now! I haven't had a minute to work on this in a while)

**Comment by TetraEtc** [comment]
That works for me :)
